name = "AoC-2022"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022, Jacob Williams"
license = "BSD-3"
description = "Advent of Code 2022 with Fortran"
homepage = "https://github.com/jacobwilliams/AoC-2022"
keywords = ["AOC"]

[dependencies]
json-fortran = { git="https://github.com/jacobwilliams/json-fortran.git", tag = "8.3.0" }

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = false
